### ISSUE TITLE
Arithmetische Operatoren kopieren Operanden

### ISSUE THREAD

**Issue by Timmifixedit** [teamspatzenhirn/SI#4]
Das ist unkritisch, wenn man mit ind oder double z.B. multipliziert. Allerdings könnte ich ja auch mit irgendeiner Skalarklasse multiplizieren (vorausgesetzt, die hat einen *-Operator), die einen Wert wrappt und deshalb deutlich größer ist, als so ein double.
Auf cppreference machen die schon bei einem Complex-Typen alles mit const-Referenzen. Wäre das hier auch sinnvoll?

**Comment by aul12** [comment]
Für normale Typen ist kopieren im Zweifelfalls besser weil der Compiler da weniger annahmen treffen muss, ich schau mal ob ich was gebaut bekomme so dass der Typ abhängig von Größe als Ref oder als Kopie übergeben wird

**Comment by aul12** [comment]
Siehe #8
