### ISSUE TITLE
/ und * Operatoren zwischen SI Typen verlangen SI-Typen mit identischem value typy

### ISSUE THREAD

**Issue by Timmifixedit** [teamspatzenhirn/SI#5]
Hier könnte man doch auch zulassen, dass man zwei SIs mit einander verknüpft, bei dem der eine double und der andere int als value type hat und dann in dem Fall z.B. das Resultat als value type double hat, oder?

**Comment by aul12** [comment]
Allgemeine Entscheidung: die Typen müssen identisch sein. Dadurch kann es nicht zu impliziten Konvertierungen kommen.
